- name: install apache2 and php package
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: install apache and php for CentOS servers
  tags: apache,apache2,centos
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"

- name: start httpd (Ubuntu)
  tags: apache,ubuntu,apache2
  service:
    name: apache2
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: change e-mail address for admin
  tags: apache,ubuntu,apache2
  lineinfile:
    path: /etc/apache2/sites-enabled/000-default.conf
    regexp: "ServerrAdmin"
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "Ubuntu"
  register: apache2

- name: restart apache2 (Ubuntu)
  tags: apache,ubuntu,apache2
  service:
    name: apache2
    state: restarted
  when: apache2.changed

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
