- name: install apache2 and php package
  tags: apache,apache2,ubuntu
  package:
    name:
      - "{{ apache_package_name}}"
      - "{{ php_package_name }}"
    state: latest

- name: install apache and php for CentOS servers
  tags: apache,apache2,centos
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"

- name: start httpd (Ubuntu)
  tags: apache,ubuntu,apache2
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: change e-mail address for admin
  tags: apache,ubuntu,apache2
  lineinfile:
    path: /etc/apache2/sites-enabled/000-default.conf
    regexp: "ServerAdmin"
    line: ServerAdmin somebody@somewhere.dk
  notify: restart_apache

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
